### ISSUE TITLE
total hexagons of a project

### ISSUE THREAD

**Issue by MartijnHeuff** [Geodan/Earthwatchers#31]
for statistics it would be nice to calculate the percentage of progress
but there is not yet a way to determine the total of hexagons of a project polygon

**Comment by bertt** [comment]
interesting function to develop! hexagons = hexagonsInPolygon(polygon,hexagonlevel)
a somewhat related function we could use is getting the list of 6 neighbour hexagons of a given hexagon. For each of these we can determine or they are within the boundary of polygon and iterate on that.

**Comment by MartijnHeuff** [comment]
The total hexagons of a polygon polygon are calculated every time a page is loaded. It would be wiser to set the total hexagons in the project.geojson after it has been calculated.

**Comment by MartijnHeuff** [comment]
To show the calculated hexagons gives a good result I made all calculated hexagons in a project visible for two projects:

![image](https://cloud.githubusercontent.com/assets/6648686/7677056/4e0f7e2e-fd49-11e4-875e-007f9a662753.png)

![image](https://cloud.githubusercontent.com/assets/6648686/7677016/0b70cf82-fd49-11e4-8c38-ae6d46731730.png)
